"""translation_cache table

Revision ID: 56d5edb9b8bb
Revises: 68567d944cf2
Create Date: 2026-05-15 14:30:58.542779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56d5edb9b8bb'
down_revision: Union[str, Sequence[str], None] = '68567d944cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lang', 'content_hash', name='uq_translation_cache_lang_hash')
    )
    op.create_index(op.f('ix_translation_cache_content_hash'), 'translation_cache', ['content_hash'], unique=False)
    op.create_index(op.f('ix_translation_cache_lang'), 'translation_cache', ['lang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_cache_lang'), table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_content_hash'), table_name='translation_cache')
    op.drop_table('translation_cache')
    # ### end Alembic commands ###
