"""suppliers and verifiable_credentials

Revision ID: 6c830d8ad74e
Revises: 56d5edb9b8bb
Create Date: 2026-05-15 16:03:40.784221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c830d8ad74e'
down_revision: Union[str, Sequence[str], None] = '56d5edb9b8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('did', sa.String(length=255), nullable=False),
    sa.Column('public_key_bytes', sa.LargeBinary(length=32), nullable=False),
    sa.Column('private_key_bytes', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_suppliers_did'), 'suppliers', ['did'], unique=True)
    op.create_table('verifiable_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dpp_record_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('attestation_type', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=512), nullable=False),
    sa.Column('jwt', sa.Text(), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpp_record_id'], ['dpp_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifiable_credentials')
    op.drop_index(op.f('ix_suppliers_did'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
