"""anchor_proofs

Revision ID: d5d7cfc145e8
Revises: 6c830d8ad74e
Create Date: 2026-05-15 16:26:30.848844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d7cfc145e8'
down_revision: Union[str, Sequence[str], None] = '6c830d8ad74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchor_proofs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dpp_record_id', sa.Uuid(), nullable=False),
    sa.Column('chain', sa.String(length=64), nullable=False),
    sa.Column('snapshot_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('explorer_tx_url', sa.String(length=512), nullable=True),
    sa.Column('anchored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpp_record_id'], ['dpp_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_anchor_proofs_snapshot_hash'), 'anchor_proofs', ['snapshot_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anchor_proofs_snapshot_hash'), table_name='anchor_proofs')
    op.drop_table('anchor_proofs')
    # ### end Alembic commands ###
